name: Check Evidence
on:
    push:
        branches: [ master ]
    pull_request:
    workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install collective-cli
      run: cargo install --git https://github.com/super-collective/collective-cli --locked -q

    - name: Validate files
      run: |
        collective check evidence

    - name: Check Index Links
      run: |
        collective index evidence
        [ -z "$(git status --porcelain)" ] || (echo "Please run 'collective index evidence' and commit the changes." && exit 1)

    - name: Check Modified Index Links
      run: |
        collective index evidence --reindex
        [ -z "$(git status --porcelain)" ] || (echo "Please run 'collective index evidence --reindex' and commit the changes." && exit 1)
