name: Check Evidence
on:
  - push
  - pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install CLI
      run: cargo install --git https://github.com/super-collective/collective-cli --locked -q

    - name: Validate files
      run: |
        collective check evidence
    
    - name: Check Index Links
      run: |
        collective index evidence
        git diff --exit-code || (echo "Index links are not up to date. Please run 'collective index evidence' and commit the changes." && exit 1)

    - name: Check Modified Index Links
      run: |
          collective index evidence --reindex
          git diff --exit-code || (echo "Index links are not up to date. Please run 'collective index evidence --reindex' and commit the changes." && exit 1)
